conference-app:
  global:
  security:
    allowInsecureImages: true

  redis:
    image:
      registry: docker.io
      repository: bitnamilegacy/redis
      tag: 7.0.11-debian-11-r12

  postgresql:
    image:
      registry: docker.io
      repository: bitnamilegacy/postgresql
      tag: 15.3.0-debian-11-r17

  kafka:
    image:
      registry: docker.io
      repository: bitnamilegacy/kafka
      tag: 3.4.1-debian-11-r0
